language: elixir
sudo: false
elixir: 1.7.1
otp_release: 20.3
notifications:
  recipients:
    - jose.valim@plataformatec.com.br
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
env:
  - MIX_ENV=test
script:
  - mix do local.hex --force
  - mix deps.get
  - mix test
  - mix coveralls.travis
  - bash test/prerelease.sh
  - npm install
  - npm run lint
  - npm run test
cache:
  directories:
    - node_modules
    - deps
addons:
  firefox: "54.0"
